version: '3'
services:
  server:
    image: nginx:latest
    volumes:
      - ./site:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/my-site.com.crt:/etc/nginx/my-site.com.crt # nginx SSL certification
      - ./nginx/my-site.com.key:/etc/nginx/my-site.com.key # nginx SSL key
    ports:
    - "443:443"
    - "8080:80"
